---
# tasks file for local-storage

- name: Instalaci√≥n de paquetes para gestionar almacenamiento local
  apt: pkg={{ item }} state=installed
  with_items:
    - lvm2
    - nfs-kernel-server
    - nfs-common
    - portmap
    - iotop
    - smartmontools
    - gparted
    - gnome-disk-utility
    - cryptsetup
  tags:
    - desktop_local_storage

- name: Copy trim settings for SSD local disk
  copy: src=etc/cron.daily/fstrim dest=/etc/cron.daily/fstrim owner=root group=root mode=755
  tags:
    - desktop_local_storage
